name: Build and Deploy to Hostinger Branch

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'

      - name: Install dependencies
        run: npm ci

      - name: Build static files
        run: npm run build

      # Deploy the contents of 'out' directory to 'hostinger' branch
      - name: Deploy to hostinger branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: hostinger
